version: '2'

services:

  dms:
    image: andrglo/everest:16.16.0
    hostname: sql-view
    container_name: sql-view-dms-1
    command: tail -f /dev/null
    working_dir: /root/sql-view
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/sql-view
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - MSSQL_HOST=mssql
      - MSSQL_PASSWORD=Passw0rd
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU11-ubuntu-20.04
    container_name: sql-view-mssql-1
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    restart: always

  postgres:
    image: postgres:12.2-alpine
    container_name: sql-view-postgres-1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always


