version: '2'

services:

  dms:
    image: andrglo/everest:12.13.0
    hostname: sql-view
    command: tail -f /dev/null
    working_dir: /root/sql-view
    volumes:
      - ./docker_fish_history:/root/.config/fish/fish_history
      - .:/root/sql-view
    environment:
      - NODE_ENV=test
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - MSSQL_HOST=mssql
      - MSSQL_PASSWORD=Passw0rd
    restart: always

  mssql:
    image: mcr.microsoft.com/mssql/server:2017-CU17
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
    restart: always

  postgres:
      image: postgres:11.2-alpine
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      restart: always


